export const ACCOUNT_KEY = 'UPDATE_CUENTA';
export const EXPLORE_B2B_KEY = 'UPDATE_DESCUBRI_B2B';
export const EXPLORE_B2C_KEY = 'UPDATE_DESCUBRI_B2C';
export const SUPPORT_KEY = 'UPDATE_SOPORTE';
export const PROFILE_KEY = 'UPDATE_PERFIL';